rj.unify.engine.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
rj.unify.engine.datasource.url=jdbc:mysql://k8s-bj-test-nodeports.ruijie.com.cn:31563/unify_engine?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
rj.unify.engine.datasource.username=root
rj.unify.engine.datasource.password=d934ba4dba9c4282803531cda85664c9
rj.unify.engine.datasource.type=com.alibaba.druid.pool.DruidDataSource
rj.unify.engine.datasource.initialSize=5
rj.unify.engine.datasource.minIdle=5
rj.unify.engine.datasource.maxActive=20
# 配置获取连接等待超时的时间
rj.unify.engine.datasource.maxWait=60000
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
rj.unify.engine.datasource.timeBetweenEvictionRunsMillis=30000
# 配置一个连接在池中最小生存的时间，单位是毫秒
rj.unify.engine.datasource.minEvictableIdleTimeMillis=30000
rj.unify.engine.datasource.validationQuery=SELECT 1 FROM DUAL
rj.unify.engine.datasource.testWhileIdle=true
rj.unify.engine.datasource.testOnBorrow=false
rj.unify.engine.datasource.testOnReturn=false
# 打开PSCache，并且指定每个连接上PSCache的大小
rj.unify.engine.datasource.poolPreparedStatements=true
rj.unify.engine.datasource.maxPoolPreparedStatementPerConnectionSize=20
rj.unify.engine.datasource.filters=stat,wall

logging.level.com.ruijie.uspportal.rjmodel.dao=DEBUG
logging.level.com.ruijie.uspportal=DEBUG
spring.flyway.validate-on-migrate=false